### ISSUE TITLE
Fails to build on Ubuntu 20.10

### ISSUE THREAD

**Issue by reinauer** [piksel/pytouch-cube#3]
Not sure how to run / build this, I tried:

python3 setup.py py2app

and got 
```
*** using recipe: subprocess *** {'expected_missing_imports': {'_winapi'}}
--- Skipping recipe botocore ---
--- Skipping recipe pyenchant ---
--- Skipping recipe pygame ---
--- Skipping recipe pyside ---
--- Skipping recipe pyside2 ---
--- Skipping recipe pyzmq ---
--- Skipping recipe qt5 ---
--- Skipping recipe shiboken2 ---
--- Skipping recipe sysconfig_module ---
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/stepan/.local/lib/python3.8/site-packages/py2app/build_app.py", line 838, in run
    self._run()
  File "/home/stepan/.local/lib/python3.8/site-packages/py2app/build_app.py", line 1053, in _run
    self.run_normal()
  File "/home/stepan/.local/lib/python3.8/site-packages/py2app/build_app.py", line 1150, in run_normal
    self.process_recipes(mf, filters, flatpackages, loader_files)
  File "/home/stepan/.local/lib/python3.8/site-packages/py2app/build_app.py", line 1007, in process_recipes
    rval = check(self, mf)
  File "/home/stepan/.local/lib/python3.8/site-packages/py2app/recipes/tkinter.py", line 48, in check
    """) % dict(tcl_path=tcl_path, tk_path=tk_path)
UnboundLocalError: local variable 'tk_path' referenced before assignment
```

**Comment by reinauer** [comment]
Full error message:

<details>
<summary><code>~/git/pytouch-cube$ python3 setup.py py2app</code></summary>

```
running py2app
creating /home/stepan/git/pytouch-cube/build/bdist.linux-x86_64/python3.8-standalone/app
creating /home/stepan/git/pytouch-cube/build/bdist.linux-x86_64/python3.8-standalone/app/collect
creating /home/stepan/git/pytouch-cube/build/bdist.linux-x86_64/python3.8-standalone/app/temp
creating build/bdist.linux-x86_64/python3.8-standalone/app/lib-dynload
creating build/bdist.linux-x86_64/python3.8-standalone/app/Frameworks
--- Skipping recipe PIL ---
--- Skipping recipe botocore ---
CTYPES USERS [SourceModule('ctypes._endian', '/usr/lib/python3.8/ctypes/_endian.py'), Package('test.support', '/usr/lib/python3.8/test/support/__init__.py', ['/usr/lib/python3.8/test/support']), SourceModule('ctypes.wintypes', '/usr/lib/python3.8/ctypes/wintypes.py'), MissingModule('ctypes.macholib.dyld',), SourceModule('ctypes._aix', '/usr/lib/python3.8/ctypes/_aix.py'), SourceModule('ctypes.util', '/usr/lib/python3.8/ctypes/util.py'), SourceModule('multiprocessing.sharedctypes', '/usr/lib/python3.8/multiprocessing/sharedctypes.py'), SourceModule('labelmaker', '/home/stepan/git/pytouch-cube/labelmaker.py'), SourceModule('serial.serialwin32', '/home/stepan/.local/lib/python3.8/site-packages/serial/serialwin32.py'), SourceModule('serial.win32', '/home/stepan/.local/lib/python3.8/site-packages/serial/win32.py'), SourceModule('serial.tools.list_ports_windows', '/home/stepan/.local/lib/python3.8/site-packages/serial/tools/list_ports_windows.py'), SourceModule('serial.tools.list_ports_osx', '/home/stepan/.local/lib/python3.8/site-packages/serial/tools/list_ports_osx.py'), SourceModule('mac_bt', '/home/stepan/git/pytouch-cube/mac_bt.py'), SourceModule('appdirs', '/usr/lib/python3/dist-packages/appdirs.py')]
*** using recipe: ctypes *** {'prescripts': ['py2app.bootstrap.ctypes_setup']}
--- Skipping recipe PIL ---
--- Skipping recipe botocore ---
--- Skipping recipe docutils ---
*** using recipe: ftplib *** {}
--- Skipping recipe PIL ---
--- Skipping recipe botocore ---
--- Skipping recipe docutils ---
*** using recipe: importlib *** {'expected_missing_imports': {'_frozen_importlib_external'}}
--- Skipping recipe PIL ---
--- Skipping recipe botocore ---
--- Skipping recipe docutils ---
--- Skipping recipe lxml ---
--- Skipping recipe matplotlib ---
*** using recipe: mimetypes *** {'expected_missing_imports': {'winreg'}}
--- Skipping recipe PIL ---
--- Skipping recipe botocore ---
--- Skipping recipe docutils ---
--- Skipping recipe lxml ---
--- Skipping recipe matplotlib ---
--- Skipping recipe numpy ---
*** using recipe: os_module *** {'expected_missing_imports': {'nt'}}
--- Skipping recipe PIL ---
--- Skipping recipe botocore ---
--- Skipping recipe docutils ---
--- Skipping recipe lxml ---
--- Skipping recipe matplotlib ---
--- Skipping recipe numpy ---
--- Skipping recipe pycryptodome ---
*** using recipe: pydoc *** {}
--- Skipping recipe PIL ---
--- Skipping recipe botocore ---
--- Skipping recipe docutils ---
--- Skipping recipe lxml ---
--- Skipping recipe matplotlib ---
--- Skipping recipe numpy ---
--- Skipping recipe pycryptodome ---
--- Skipping recipe pyenchant ---
--- Skipping recipe pygame ---
--- Skipping recipe pyopengl ---
--- Skipping recipe pyside ---
--- Skipping recipe pyside2 ---
--- Skipping recipe pyzmq ---
--- Skipping recipe qt5 ---
*** using recipe: re *** {'expected_missing_imports': {'sys.getwindowsversion'}}
--- Skipping recipe PIL ---
--- Skipping recipe botocore ---
--- Skipping recipe docutils ---
--- Skipping recipe lxml ---
--- Skipping recipe matplotlib ---
--- Skipping recipe numpy ---
--- Skipping recipe pycryptodome ---
--- Skipping recipe pyenchant ---
--- Skipping recipe pygame ---
--- Skipping recipe pyopengl ---
--- Skipping recipe pyside ---
--- Skipping recipe pyside2 ---
--- Skipping recipe pyzmq ---
--- Skipping recipe qt5 ---
--- Skipping recipe scipy ---
*** using recipe: setuptools *** {'expected_missing_imports': {'pkg_resources._vendor.appdirs', 'pkg_resources.extern.pyparsing', 'pkg_resources.extern.six', '__main__.__requires__', '__builtin__'}}
--- Skipping recipe PIL ---
--- Skipping recipe botocore ---
--- Skipping recipe docutils ---
--- Skipping recipe lxml ---
--- Skipping recipe matplotlib ---
--- Skipping recipe numpy ---
--- Skipping recipe pycryptodome ---
--- Skipping recipe pyenchant ---
--- Skipping recipe pygame ---
--- Skipping recipe pyopengl ---
--- Skipping recipe pyside ---
--- Skipping recipe pyside2 ---
--- Skipping recipe pyzmq ---
--- Skipping recipe qt5 ---
--- Skipping recipe scipy ---
--- Skipping recipe shiboken2 ---
sip: packages: {'chardet-3.0.4.egg-info', 'debian_bundle', 'CommandNotFound', 'httplib2', 'PyQt5.__pycache__', 'scipy-1.5.2.egg-info', 'PyQt5.QtPrintSupport.cpython-38-x86_64-linux-gnu', 'zope', 'cryptography-3.0.egg-info', 'pytz', 'PyQt5.Qt.cpython-38-x86_64-linux-gnu', 'distro_info-0.23ubuntu1.egg-info', 'apt_pkg-stubs', 'OpenGL', 'OpenSSL', 'cupshelpers', 'google', 'PyJWT-1.7.1.egg-info', 'wsproto', 'Jinja2-2.11.2.egg-info', 'TkTreectrl', 'pyatspi', 'urllib3-1.25.9.egg-info', 'wx', 'markdown', 'pyparsing-2.4.7.egg-info', 'crcmod', 'itsdangerous-1.1.0.egg-info', 'dbus', 'hpack', 'hpack-3.0.0.egg-info', 'virtualenv', 'PyQt5.QtHelp.cpython-38-x86_64-linux-gnu', 'pymacaroons-0.13.0.egg-info', 'pyusb-1.0.2.egg-info', 'pyqtgraph-0.11.0.egg-info', 'PyQt5._QOpenGLFunctions_4_1_Core.cpython-38-x86_64-linux-gnu', 'ruamel.yaml.clib-0.2.0.egg-info', 'h11', 'httplib2-0.18.1.egg-info', 'certbot-1.7.0.egg-info', 'setuptools', 'appdirs-1.4.4.egg-info', 'mitmproxy-5.1.1.egg-info', 'ibus_cangjie', 'colorama', 'yaml', 'chardet', '_distutils_hack', 'wadllib', 'tornado', 'parsedatetime', 'keyring-21.3.0.egg-info', 'acme-1.6.0.egg-info', 'bs4', 'more_itertools-4.2.0.egg-info', 'numpy', 'speechd_config', 'dbus_python-1.2.16.egg-info', 'PyQt5-5.15.0.dist-info', 'ufw', 'six-1.15.0.egg-info', 'ldap3-2.7.egg-info', 'Crypto', 'duplicity-0.8.12.0.egg-info', 'passlib', 'PyNaCl-1.4.0.egg-info', 'requests_toolbelt', 'ssh_import_id-5.10.egg-info', 'PyQt5.QtDBus.cpython-38-x86_64-linux-gnu', 'ruamel', 'DistUpgrade', 'wsproto-0.15.0.egg-info', 'lxml-4.5.2.egg-info', 'debian', 'defer', 'urwid', 'sip-4.19.24.dist-info', 'importlib_metadata-1.6.0.egg-info', 'macaroonbakery', 'mpl_toolkits', 'launchpadlib-1.10.13.egg-info', 'past', 'PIL', 'lazr.uri-1.0.5.egg-info', 'markupsafe', 'Cryptodome', 'Werkzeug-1.0.1.egg-info', 'intelhex', 'aptdaemon', 'reportlab', 'pyasn1', 'ruamel.yaml-0.16.12.egg-info', 'python_debian-0.1.37.egg-info', 'decorator-4.4.2.egg-info', 'h2-3.2.0.egg-info', 'acme', 'PyQt5.pylupdate.cpython-38-x86_64-linux-gnu', 'ecdsa', 'pip', 'orca', 'wadllib-1.3.4.egg-info', 'matplotlib', 'Markdown-3.2.2.egg-info', 'certifi-2020.4.5.1.egg-info', 'SSSDConfig', 'colorama-0.4.3.egg-info', 'h11-0.9.0.egg-info', 'LanguageSelector', 'idna', 'mako', 'distlib-0.3.1.egg-info', 'idna-2.10.egg-info', 'soupsieve-2.0.1.egg-info', 'softwareproperties', 'pyperclip-1.8.0.egg-info', 'future-0.18.2.egg-info', 'PyQt5.QtOpenGL.cpython-38-x86_64-linux-gnu', 'binwalk', 'libfuturize', 'monotonic-1.5.egg-info', 'pygments', 'pygtkcompat', 'uaclient', 'zipp-1.0.0.egg-info', 'requests_toolbelt-0.8.0.egg-info', 'lazr.restfulclient-0.14.2.egg-info', 'josepy-1.2.0.egg-info', 'html5lib-1.1.egg-info', 'sortedcontainers', 'PyQt5.QtWidgets.cpython-38-x86_64-linux-gnu', 'jwt', 'virtualenv-20.0.29+ds.egg-info', 'python_dateutil-2.8.1.egg-info', 'ecdsa-0.15.egg-info', 'lockfile', 'pyqtgraph', 'apport', 'ConfigArgParse-0.13.0.egg-info', 'youtube_dl-2020.9.14.egg-info', 'icu', 'numpy-1.18.4.egg-info', 'itsdangerous', 'distlib', 'PyGObject-3.38.0.egg-info', 'click-7.1.2.egg-info', 'pyasn1-0.4.8.egg-info', 'importlib_metadata', 'lxml', 'unattended_upgrades-0.1.egg-info', 'hyperframe-5.2.0.egg-info', 'certifi', 'publicsuffix2-2.20191221.egg-info', 'UbuntuDrivers', 'PyQt5.QtTest.cpython-38-x86_64-linux-gnu', 'ptyprocess', 'h2', 'gi', 'defer-1.0.6.egg-info', 'samba', 'pycryptodomex-3.9.7.egg-info', 'HweSupportStatus', 'UpdateManager', 'language_selector-0.1.egg-info', 'sortedcontainers-2.1.0.egg-info', 'click', 'requests_unixsocket', 'scour', 'flask', 'Pygments-2.3.1.egg-info', 'Pillow-7.2.0.egg-info', 'beautifulsoup4-4.9.1.egg-info', 'oauthlib', 'kaitaistruct-0.8.egg-info', 'ubuntu_drivers_common-0.0.0.egg-info', 'cangjie', 'PyQt5._QOpenGLFunctions_2_1.cpython-38-x86_64-linux-gnu', 'Mako-1.1.2.egg-info', 'MarkupSafe-1.1.1.egg-info', 'systemd', 'publicsuffix2', 'zope.interface-4.7.1.egg-info', 'pexpect', 'protobuf-3.12.3.egg-info', 'NvidiaDetector', 'olefile', 'pkg_resources', 'lazr', 'dnspython-1.16.0.egg-info', 'ldap3', 'wheel-0.34.2.egg-info', 'youtube_dl', 'PyQt5.uic', 'pyrfc3339', 'speechd', 'apt_inst-stubs', 'Quirks', 'pathod', 'urllib3', 'matplotlib-3.3.0.egg-info', 'pyRFC3339-1.1.egg-info', 'passlib-1.7.2.egg-info', 'cairo', 'bcrypt-3.1.7.egg-info', 'wheel', 'paramiko', 'requests_unixsocket-0.2.0.egg-info', 'macaroonbakery-1.3.1.egg-info', 'PyQt5', 'paramiko-2.7.1.egg-info', 'secretstorage', 'duplicity', 'SecretStorage-3.1.2.egg-info', 'pyOpenSSL-19.1.0.egg-info', 'ubuntu_advantage_tools-24.4.egg-info', 'Flask-1.1.2.egg-info', 'ssh_import_id', 'dateutil', 'zope.component-4.3.0.egg-info', 'hyperframe', 'python_apt-2.1.3+ubuntu1.3.egg-info', 'future', 'janitor', 'lockfile-0.12.2.egg-info', 'wxPython-4.0.7.egg-info', 'tornado-6.0.4.egg-info', 'simplejson', 'configobj-5.0.6.egg-info', 'apt', 'louis', 'josepy', 'werkzeug', 'mitmproxy', 'usb', 'reportlab-3.5.47.egg-info', 'Brotli-1.0.9.egg-info', 'urwid-2.1.1.egg-info', 'pyperclip', 'fasteners', 'pymacaroons', 'soupsieve', 'xkit', 'PyQt5._QOpenGLFunctions_2_0.cpython-38-x86_64-linux-gnu', 'kiwisolver-1.2.0.egg-info', 'jinja2', 'nacl', '__pycache__', 'zope.event-4.4.egg-info', 'gpg', 'filelock-3.0.12.egg-info', 'blinker', 'jeepney', 'pyxattr-0.6.1.egg-info', 'cycler-0.10.0.egg-info', 'oauthlib-3.1.0.egg-info', 'aptsources', 'PyQt5.QtDesigner.cpython-38-x86_64-linux-gnu', 'olefile-0.46.egg-info', 'pip-20.1.1.egg-info', 'PyQt5.QtCore.cpython-38-x86_64-linux-gnu', 'bcrypt', 'PyQt5.QtXml.cpython-38-x86_64-linux-gnu', 'webencodings', 'PyQt5.pyrcc.cpython-38-x86_64-linux-gnu', 'webencodings-0.5.1.egg-info', 'fasteners-0.14.1.egg-info', 'AptUrl', 'parsedatetime-2.4.egg-info', 'dns', 'more_itertools', 'setuptools-49.3.1.egg-info', 'PyOpenGL-3.1.5.egg-info', 'certbot', 'zope.hookable-5.0.1.egg-info', 'netifaces-0.10.4.egg-info', 'cryptography', 'blueman', 'distro-1.5.0.egg-info', 'pytz-2020.1.egg-info', 'PyQt5.QtGui.cpython-38-x86_64-linux-gnu', 'usbcreator', 'scour-0.37.egg-info', 'requests-2.23.0.egg-info', 'launchpadlib', 'requests', 'scipy', 'PyQt5.QtNetwork.cpython-38-x86_64-linux-gnu', 'libpasteurize', 'html5lib', 'keyring', 'xdg'}
WARNING: ImportError in sip recipe ignored: No module named chardet-3
WARNING: ImportError in sip recipe ignored: No module named scipy-1
WARNING: ImportError in sip recipe ignored: No module named cryptography-3
WARNING: ImportError in sip recipe ignored: No module named distro_info-0
WARNING: ImportError in sip recipe ignored: No module named PyJWT-1
WARNING: ImportError in sip recipe ignored: No module named Jinja2-2
WARNING: ImportError in sip recipe ignored: No module named urllib3-1
WARNING: ImportError in sip recipe ignored: No module named pyparsing-2
WARNING: ImportError in sip recipe ignored: No module named itsdangerous-1
WARNING: ImportError in sip recipe ignored: No module named hpack-3
WARNING: ImportError in sip recipe ignored: No module named pymacaroons-0
WARNING: ImportError in sip recipe ignored: No module named pyusb-1
WARNING: ImportError in sip recipe ignored: No module named pyqtgraph-0
WARNING: ImportError in sip recipe ignored: No module named httplib2-0
WARNING: ImportError in sip recipe ignored: No module named certbot-1
WARNING: ImportError in sip recipe ignored: No module named appdirs-1
WARNING: ImportError in sip recipe ignored: No module named mitmproxy-5
WARNING: ImportError in sip recipe ignored: No module named keyring-21
WARNING: ImportError in sip recipe ignored: No module named acme-1
WARNING: ImportError in sip recipe ignored: No module named more_itertools-4
WARNING: ImportError in sip recipe ignored: No module named dbus_python-1
WARNING: ImportError in sip recipe ignored: No module named PyQt5-5
WARNING: ImportError in sip recipe ignored: No module named six-1
WARNING: ImportError in sip recipe ignored: No module named ldap3-2
WARNING: ImportError in sip recipe ignored: No module named duplicity-0
WARNING: ImportError in sip recipe ignored: No module named PyNaCl-1
WARNING: ImportError in sip recipe ignored: No module named ssh_import_id-5
WARNING: ImportError in sip recipe ignored: No module named wsproto-0
WARNING: ImportError in sip recipe ignored: No module named lxml-4
WARNING: ImportError in sip recipe ignored: No module named sip-4
WARNING: ImportError in sip recipe ignored: No module named importlib_metadata-1
WARNING: ImportError in sip recipe ignored: No module named launchpadlib-1
WARNING: ImportError in sip recipe ignored: No module named Werkzeug-1
WARNING: ImportError in sip recipe ignored: No module named python_debian-0
WARNING: ImportError in sip recipe ignored: No module named decorator-4
WARNING: ImportError in sip recipe ignored: No module named h2-3
WARNING: ImportError in sip recipe ignored: No module named wadllib-1
WARNING: ImportError in sip recipe ignored: No module named Markdown-3
WARNING: ImportError in sip recipe ignored: No module named certifi-2020
WARNING: ImportError in sip recipe ignored: No module named colorama-0
WARNING: ImportError in sip recipe ignored: No module named h11-0
WARNING: ImportError in sip recipe ignored: No module named distlib-0
WARNING: ImportError in sip recipe ignored: No module named idna-2
WARNING: ImportError in sip recipe ignored: No module named soupsieve-2
WARNING: ImportError in sip recipe ignored: No module named pyperclip-1
WARNING: ImportError in sip recipe ignored: No module named future-0
WARNING: ImportError in sip recipe ignored: No module named monotonic-1
WARNING: ImportError in sip recipe ignored: No module named zipp-1
WARNING: ImportError in sip recipe ignored: No module named requests_toolbelt-0
WARNING: ImportError in sip recipe ignored: No module named josepy-1
WARNING: ImportError in sip recipe ignored: No module named html5lib-1
WARNING: ImportError in sip recipe ignored: No module named virtualenv-20
WARNING: ImportError in sip recipe ignored: No module named python_dateutil-2
WARNING: ImportError in sip recipe ignored: No module named ecdsa-0
WARNING: ImportError in sip recipe ignored: No module named ConfigArgParse-0
WARNING: ImportError in sip recipe ignored: No module named youtube_dl-2020
WARNING: ImportError in sip recipe ignored: No module named numpy-1
WARNING: ImportError in sip recipe ignored: No module named PyGObject-3
WARNING: ImportError in sip recipe ignored: No module named click-7
WARNING: ImportError in sip recipe ignored: No module named pyasn1-0
WARNING: ImportError in sip recipe ignored: No module named unattended_upgrades-0
WARNING: ImportError in sip recipe ignored: No module named hyperframe-5
WARNING: ImportError in sip recipe ignored: No module named publicsuffix2-2
WARNING: ImportError in sip recipe ignored: No module named defer-1
WARNING: ImportError in sip recipe ignored: No module named pycryptodomex-3
WARNING: ImportError in sip recipe ignored: No module named language_selector-0
WARNING: ImportError in sip recipe ignored: No module named sortedcontainers-2
WARNING: ImportError in sip recipe ignored: No module named Pygments-2
WARNING: ImportError in sip recipe ignored: No module named Pillow-7
WARNING: ImportError in sip recipe ignored: No module named beautifulsoup4-4
WARNING: ImportError in sip recipe ignored: No module named kaitaistruct-0
WARNING: ImportError in sip recipe ignored: No module named ubuntu_drivers_common-0
WARNING: ImportError in sip recipe ignored: No module named Mako-1
WARNING: ImportError in sip recipe ignored: No module named MarkupSafe-1
WARNING: ImportError in sip recipe ignored: No module named protobuf-3
WARNING: ImportError in sip recipe ignored: No module named dnspython-1
WARNING: ImportError in sip recipe ignored: No module named wheel-0
WARNING: ImportError in sip recipe ignored: No module named matplotlib-3
WARNING: ImportError in sip recipe ignored: No module named pyRFC3339-1
WARNING: ImportError in sip recipe ignored: No module named passlib-1
WARNING: ImportError in sip recipe ignored: No module named bcrypt-3
WARNING: ImportError in sip recipe ignored: No module named requests_unixsocket-0
WARNING: ImportError in sip recipe ignored: No module named macaroonbakery-1
WARNING: ImportError in sip recipe ignored: No module named paramiko-2
WARNING: ImportError in sip recipe ignored: No module named SecretStorage-3
WARNING: ImportError in sip recipe ignored: No module named pyOpenSSL-19
WARNING: ImportError in sip recipe ignored: No module named ubuntu_advantage_tools-24
WARNING: ImportError in sip recipe ignored: No module named Flask-1
WARNING: ImportError in sip recipe ignored: No module named python_apt-2
WARNING: ImportError in sip recipe ignored: No module named lockfile-0
WARNING: ImportError in sip recipe ignored: No module named wxPython-4
WARNING: ImportError in sip recipe ignored: No module named tornado-6
WARNING: ImportError in sip recipe ignored: No module named configobj-5
WARNING: ImportError in sip recipe ignored: No module named reportlab-3
WARNING: ImportError in sip recipe ignored: No module named Brotli-1
WARNING: ImportError in sip recipe ignored: No module named urwid-2
WARNING: ImportError in sip recipe ignored: No module named kiwisolver-1
WARNING: ImportError in sip recipe ignored: No module named filelock-3
WARNING: ImportError in sip recipe ignored: No module named pyxattr-0
WARNING: ImportError in sip recipe ignored: No module named cycler-0
WARNING: ImportError in sip recipe ignored: No module named oauthlib-3
WARNING: ImportError in sip recipe ignored: No module named olefile-0
WARNING: ImportError in sip recipe ignored: No module named pip-20
WARNING: ImportError in sip recipe ignored: No module named webencodings-0
WARNING: ImportError in sip recipe ignored: No module named fasteners-0
WARNING: ImportError in sip recipe ignored: No module named parsedatetime-2
WARNING: ImportError in sip recipe ignored: No module named setuptools-49
WARNING: ImportError in sip recipe ignored: No module named PyOpenGL-3
WARNING: ImportError in sip recipe ignored: No module named netifaces-0
WARNING: ImportError in sip recipe ignored: No module named distro-1
WARNING: ImportError in sip recipe ignored: No module named pytz-2020
WARNING: ImportError in sip recipe ignored: No module named scour-0
WARNING: ImportError in sip recipe ignored: No module named requests-2
*** using recipe: sip *** {'resources': ['/usr/local/lib/python3.8/dist-packages/py2app/recipes/qt.conf']}
*** using recipe: PIL *** {'prescripts': ['py2app.recipes.PIL.prescript', <_io.StringIO object at 0x7f19531e8af0>], 'include': 'PIL.JpegPresets', 'flatpackages': ['/usr/lib/python3/dist-packages/PIL']}
--- Skipping recipe botocore ---
--- Skipping recipe docutils ---
*** using recipe: lxml *** {}
--- Skipping recipe botocore ---
--- Skipping recipe docutils ---
*** using recipe: matplotlib *** {'prescripts': ['py2app.recipes.matplotlib_prescript'], 'resources': ['/home/stepan/.local/lib/python3.8/site-packages/matplotlib/mpl-data'], 'packages': ['matplotlib']}
--- Skipping recipe botocore ---
*** using recipe: docutils *** {}
--- Skipping recipe botocore ---
*** using recipe: numpy *** {'packages': ['numpy']}
--- Skipping recipe botocore ---
*** using recipe: pycryptodome *** {'packages': ['Crypto']}
--- Skipping recipe botocore ---
--- Skipping recipe pyenchant ---
--- Skipping recipe pygame ---
*** using recipe: pyopengl *** {'packages': ['OpenGL']}
--- Skipping recipe botocore ---
--- Skipping recipe pyenchant ---
--- Skipping recipe pygame ---
--- Skipping recipe pyside ---
--- Skipping recipe pyside2 ---
--- Skipping recipe pyzmq ---
--- Skipping recipe qt5 ---
*** using recipe: scipy *** {'packages': ['scipy', 'numpy']}
--- Skipping recipe botocore ---
--- Skipping recipe pyenchant ---
--- Skipping recipe pygame ---
--- Skipping recipe pyside ---
--- Skipping recipe pyside2 ---
--- Skipping recipe pyzmq ---
--- Skipping recipe qt5 ---
--- Skipping recipe shiboken2 ---
*** using recipe: six *** {}
--- Skipping recipe botocore ---
--- Skipping recipe pyenchant ---
--- Skipping recipe pygame ---
--- Skipping recipe pyside ---
--- Skipping recipe pyside2 ---
--- Skipping recipe pyzmq ---
--- Skipping recipe qt5 ---
--- Skipping recipe shiboken2 ---
*** using recipe: subprocess *** {'expected_missing_imports': {'_winapi'}}
--- Skipping recipe botocore ---
--- Skipping recipe pyenchant ---
--- Skipping recipe pygame ---
--- Skipping recipe pyside ---
--- Skipping recipe pyside2 ---
--- Skipping recipe pyzmq ---
--- Skipping recipe qt5 ---
--- Skipping recipe shiboken2 ---
--- Skipping recipe sysconfig_module ---
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/dist-packages/py2app/build_app.py", line 925, in run
    self._run()
  File "/usr/local/lib/python3.8/dist-packages/py2app/build_app.py", line 1147, in _run
    self.run_normal()
  File "/usr/local/lib/python3.8/dist-packages/py2app/build_app.py", line 1244, in run_normal
    self.process_recipes(mf, filters, flatpackages, loader_files)
  File "/usr/local/lib/python3.8/dist-packages/py2app/build_app.py", line 1099, in process_recipes
    rval = check(self, mf)
  File "/usr/local/lib/python3.8/dist-packages/py2app/recipes/tkinter.py", line 51, in check
    % {"tcl_path": tcl_path, "tk_path": tk_path}
UnboundLocalError: local variable 'tk_path' referenced before assignment
```

</details>

**Comment by piksel** [comment]
Honestly, this is veery alpha quality. It runs on mac on windows, but I know that I have some local modifications on both machines to make them work a little bit better for each platform.
I don't currently use any linux desktop OS, but I'll see if I can get it working in a VM and let you know.

**Comment by piksel** [comment]
I updated the deps and added a package that seems to have vanished ([pyBarcode](https://bitbucket.org/whitie/python-barcode/)).

py2app is just for macos, use
```
pip3 install .
```
to install dependencies, and then
```
python3 gui.py
```
to launch the app.

**Comment by reinauer** [comment]
Ok, got a bit further... On Linux I can start the App as you described above, but can not currently seem to talk to the rfcomm0 device. 
On MacOS I can build the App, but starting it results in a "PyTouch Cube Error" which offers me to start the console, but the only thing in the logs I can find is...
com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.apple.Console.1152921500311974274.1152921500311974279(501)> [9758]
com.apple.xpc.launchd[1] (application.org.pythonmac.unspecified.PyTouchCubeEditor.12889544304.12889547414[17265]): Service exited with abnormal code: 255

**Comment by piksel** [comment]
For mac, try the [compiled binary](https://github.com/piksel/pytouch-cube/releases/tag/v0.8).
The error messages tend to be kind of bad when the crashes occur in Qt.

Does the device get listed? It should be using [pyserial's list_ports_linux](https://github.com/pyserial/pyserial/blob/master/serial/tools/list_ports_linux.py) for the port list, but since #1 was reported, maybe that's not working?
I don't have bluetooth in the VM unfortunately...

**Comment by Mimoja** [comment]
I tested build on Ubuntu 18.04, 20.04 and 22.04 with #37. Ubuntu 20.10 is EOL and should not be supported at this point. rfcomms connecting also works by now :)
