### ISSUE TITLE
Does not create default settinngs folder

### ISSUE THREAD

**Issue by tarosk** [piksel/pytouch-cube#5]
C:\Temp\pytouch-cube>gui.py
PIL not found. Image output disabled.

Traceback (most recent call last):
  File "C:\Temp\pytouch-cube\gui.py", line 585, in <module>
    PyTouchCubeGUI(QApplication([])).run()
  File "C:\Temp\pytouch-cube\gui.py", line 95, in __init__
    Settings.load()
  File "C:\Temp\pytouch-cube\settings.py", line 40, in load
    os.mkdir(config_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\ivan.tarapcik\\AppData\\Local\\piksel bitworks\\PyTouch Cube Editor'

**Comment by piksel** [comment]
Should be fixed now!
